---
- name: Enable epel repo
  ansible.builtin.yum:
    name: epel-release
    state: present
    update_cache: true
  when:
    - ansible_distribution in ['RedHat', 'Rocky']

- name: Enable repository based on distribution and version
  ansible.builtin.command: >
    dnf config-manager --set-enabled {{ item.repo }}
  changed_when: false
  loop:
    - { repo: 'crb', dist: 'RedHat', version: '9' }
    - { repo: 'powertools', dist: 'RedHat', version: '8' }
    - { repo: 'ol8_codeready_builder', dist: 'OracleLinux', version: '8' }
  when: ansible_distribution == item.dist and ansible_distribution_major_version == item.version
