name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - rocky8
          - rocky9
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: robertdebock/molecule-action@1d7bccac41a43ddd7f4faaa7775e59f0ecf7a865 # 6.0.0
        with:
          scenario: ${{ matrix.scenario }}
