name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - rocky8
          - rocky9
          - oracle8
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: robertdebock/molecule-action@d3e37309fc9c287d6a3507d172520d37df0e2dda # 6.0.1
        with:
          scenario: ${{ matrix.scenario }}
